CREATE TYPE "competition_status" AS ENUM ('draft','published','live','paused','completed','cancelled');
CREATE TYPE "entry_status" AS ENUM ('pending','approved','withdrawn','disqualified');
CREATE TYPE "round_status" AS ENUM ('scheduled','live','completed','cancelled');
CREATE TYPE "performance_status" AS ENUM ('queued','live','completed','skipped');
CREATE TYPE "result_status" AS ENUM ('provisional','final','void');
CREATE TABLE "organizations" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "name" text NOT NULL, "slug" text NOT NULL UNIQUE, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "participants" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES organizations(id), "display_name" text NOT NULL, "external_ref" text, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX "participants_external_ref_uniq" ON "participants" ("organization_id","external_ref");
CREATE INDEX "participants_organization_idx" ON "participants" ("organization_id");
CREATE UNIQUE INDEX "participants_org_id_uniq" ON "participants" ("organization_id","id");
CREATE TABLE "competitions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES organizations(id), "title" text NOT NULL, "description" text, "status" competition_status NOT NULL DEFAULT 'draft', "rules" jsonb NOT NULL DEFAULT '{}'::jsonb, "starts_at" timestamptz, "ends_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE INDEX "competitions_org_status_idx" ON "competitions" ("organization_id","status");
CREATE UNIQUE INDEX "competitions_org_id_uniq" ON "competitions" ("organization_id","id");
CREATE TABLE "entries" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES organizations(id), "competition_id" uuid NOT NULL, "participant_id" uuid NOT NULL, "status" entry_status NOT NULL DEFAULT 'pending', "created_at" timestamptz NOT NULL DEFAULT now(), FOREIGN KEY ("organization_id","competition_id") REFERENCES "competitions" ("organization_id","id"), FOREIGN KEY ("organization_id","participant_id") REFERENCES "participants" ("organization_id","id"));
CREATE UNIQUE INDEX "entries_unique_participant" ON "entries" ("competition_id","participant_id");
CREATE INDEX "entries_competition_status_idx" ON "entries" ("competition_id","status");
CREATE TABLE "rounds" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES organizations(id), "competition_id" uuid NOT NULL, "label" text NOT NULL, "ordinal" integer NOT NULL CHECK ("ordinal" > 0), "status" round_status NOT NULL DEFAULT 'scheduled', "scheduled_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), FOREIGN KEY ("organization_id","competition_id") REFERENCES "competitions" ("organization_id","id"));
CREATE UNIQUE INDEX "rounds_unique_ordinal" ON "rounds" ("competition_id","ordinal");
CREATE UNIQUE INDEX "rounds_competition_id_uniq" ON "rounds" ("competition_id","id");
CREATE TABLE "performances" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES organizations(id), "competition_id" uuid NOT NULL, "round_id" uuid NOT NULL, "entry_id" uuid NOT NULL, "ordinal" integer NOT NULL CHECK ("ordinal" > 0), "status" performance_status NOT NULL DEFAULT 'queued', "started_at" timestamptz, "completed_at" timestamptz, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, FOREIGN KEY ("organization_id","competition_id") REFERENCES "competitions" ("organization_id","id"), FOREIGN KEY ("competition_id","round_id") REFERENCES "rounds" ("competition_id","id"), FOREIGN KEY ("entry_id") REFERENCES "entries" ("id"));
CREATE UNIQUE INDEX "performances_unique_ordinal" ON "performances" ("round_id","ordinal");
CREATE INDEX "performances_round_status_idx" ON "performances" ("round_id","status");
CREATE TABLE "judges" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES organizations(id), "display_name" text NOT NULL, "external_ref" text, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE INDEX "judges_organization_idx" ON "judges" ("organization_id");
CREATE TABLE "competition_judges" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES organizations(id), "competition_id" uuid NOT NULL, "judge_id" uuid NOT NULL, FOREIGN KEY ("organization_id","competition_id") REFERENCES "competitions" ("organization_id","id"), FOREIGN KEY ("judge_id") REFERENCES "judges" ("id"));
CREATE UNIQUE INDEX "competition_judges_unique" ON "competition_judges" ("competition_id","judge_id");
CREATE TABLE "results" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organization_id" uuid NOT NULL REFERENCES organizations(id), "competition_id" uuid NOT NULL, "round_id" uuid, "entry_id" uuid NOT NULL REFERENCES entries(id), "rank" integer CHECK ("rank" > 0), "score" text, "status" result_status NOT NULL DEFAULT 'provisional', "details" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now(), FOREIGN KEY ("organization_id","competition_id") REFERENCES "competitions" ("organization_id","id"), FOREIGN KEY ("competition_id","round_id") REFERENCES "rounds" ("competition_id","id"));
CREATE INDEX "results_competition_idx" ON "results" ("competition_id","status");
